name: Deploy Green

on:
  push:
    branches:
      - test

env:
  PROJECT_ID: public-cloud-concepts-487620
  REGION: us-east1
  REPOSITORY: bluegreen
  IMAGE: green

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest .

    - name: Push Docker image
      run: docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: gk3-autopilot-cluster-1
        location: us-east1

    - name: Update Green Deployment
      run: kubectl set image deployment/green-deployment myapp=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest

